spring:
  datasource:
    url: jdbc:mysql://localhost:3306/star_core?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root123

logging:
  level:
    com.star.reward: INFO
